<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200706034328 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE medios_trans (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, basificacion VARCHAR(255) DEFAULT NULL, tipo_medio INT NOT NULL, year_fab INT NOT NULL, cap DOUBLE PRECISION DEFAULT NULL, umcap INT DEFAULT NULL, aseguramiento TINYINT(1) NOT NULL, marca INT NOT NULL, modelo INT NOT NULL, estado_medio INT NOT NULL, servicios_especiales INT DEFAULT NULL, tipo_combustible INT NOT NULL, ind_consumo DOUBLE PRECISION DEFAULT NULL, potencia INT DEFAULT NULL, tipo_propiedad INT DEFAULT NULL, rama INT NOT NULL, num_rev_tecnica VARCHAR(255) DEFAULT NULL, venc_rev_tecnica DATE DEFAULT NULL, pais_abanderamiento VARCHAR(255) DEFAULT NULL, id_tipo INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE basificacion CHANGE idmun idmun INT DEFAULT NULL, CHANGE idlicencia idlicencia VARCHAR(9) DEFAULT NULL, CHANGE NombreLB NombreLB VARCHAR(200) DEFAULT NULL, CHANGE Direccion Direccion VARCHAR(200) DEFAULT NULL');
        $this->addSql('ALTER TABLE lotjuridicas CHANGE idtramitador idtramitador INT DEFAULT NULL, CHANGE idaprueba idaprueba INT DEFAULT NULL, CHANGE idextension idextension INT DEFAULT NULL, CHANGE idrama idrama INT DEFAULT NULL, CHANGE tipomoneda tipomoneda INT DEFAULT NULL, CHANGE FechaSolicitud FechaSolicitud DATETIME DEFAULT NULL, CHANGE Presentada Presentada TINYINT(1) DEFAULT NULL, CHANGE Aprobada Aprobada TINYINT(1) DEFAULT NULL, CHANGE FechaAprobacion FechaAprobacion DATETIME DEFAULT NULL, CHANGE FechaEmision FechaEmision DATETIME DEFAULT NULL, CHANGE FechaEntrega FechaEntrega DATETIME DEFAULT NULL, CHANGE limitacion limitacion INT DEFAULT NULL, CHANGE TpoMedioAmparado TpoMedioAmparado INT DEFAULT NULL, CHANGE Duracion Duracion INT DEFAULT NULL, CHANGE FechaDeCancelacion FechaDeCancelacion DATETIME DEFAULT NULL, CHANGE FechaRenov FechaRenov DATETIME DEFAULT NULL, CHANGE Posteada Posteada TINYINT(1) DEFAULT NULL, CHANGE MediaTarifa MediaTarifa TINYINT(1) DEFAULT NULL, CHANGE MedidaDelTiempo MedidaDelTiempo VARCHAR(4) DEFAULT NULL, CHANGE NumFolio NumFolio VARCHAR(10) DEFAULT NULL, CHANGE FechaAprobInicial FechaAprobInicial DATETIME DEFAULT NULL, CHANGE TipoSolicitud TipoSolicitud INT DEFAULT NULL, CHANGE CausaDeCancelacion CausaDeCancelacion INT DEFAULT NULL, CHANGE ProrrogadoEnDias ProrrogadoEnDias SMALLINT DEFAULT NULL, CHANGE FechaDeDestruccion FechaDeDestruccion DATETIME DEFAULT NULL, CHANGE Duplicado Duplicado TINYINT(1) DEFAULT NULL, CHANGE IdEntidad IdEntidad VARCHAR(255) DEFAULT NULL, CHANGE IDTipo IDTipo INT DEFAULT NULL, CHANGE IDServicio IDServicio INT DEFAULT NULL, CHANGE ServicioAmparado ServicioAmparado INT DEFAULT NULL, CHANGE IDEstado IDEstado INT DEFAULT NULL');
        $this->addSql('ALTER TABLE municipios CHANGE provinciaid provinciaid INT DEFAULT NULL, CHANGE s_GUID s_GUID VARCHAR(50) DEFAULT NULL, CHANGE Codigo Codigo INT DEFAULT NULL, CHANGE Municipio Municipio VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE organismos CHANGE Descripcion Descripcion VARCHAR(200) DEFAULT NULL, CHANGE `Desc` `Desc` VARCHAR(200) DEFAULT NULL');
        $this->addSql('ALTER TABLE personasjuridicas CHANGE idorga idorga INT DEFAULT NULL, CHANGE idmunicipio idmunicipio INT DEFAULT NULL, CHANGE CodReeup CodReeup VARCHAR(50) DEFAULT NULL, CHANGE NomEntidad NomEntidad VARCHAR(100) DEFAULT NULL, CHANGE Telefono Telefono VARCHAR(20) DEFAULT NULL, CHANGE Email Email VARCHAR(50) DEFAULT NULL, CHANGE Direccion Direccion VARCHAR(200) DEFAULT NULL, CHANGE Actividad Actividad VARCHAR(2) DEFAULT NULL, CHANGE Rama Rama VARCHAR(2) DEFAULT NULL, CHANGE SubRama SubRama VARCHAR(2) DEFAULT NULL, CHANGE NoContribuyente NoContribuyente VARCHAR(15) DEFAULT NULL, CHANGE Representante Representante VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE provincias CHANGE s_GUID s_GUID VARCHAR(50) DEFAULT NULL, CHANGE Provincias Provincias VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE usuario CHANGE rol_id rol_id INT DEFAULT NULL, CHANGE idmunicipio idmunicipio INT DEFAULT NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE medios_trans');
        $this->addSql('ALTER TABLE basificacion CHANGE idlicencia idlicencia VARCHAR(9) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE idmun idmun INT DEFAULT NULL, CHANGE NombreLB NombreLB VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Direccion Direccion VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE lotjuridicas CHANGE idtramitador idtramitador INT DEFAULT NULL, CHANGE idaprueba idaprueba INT DEFAULT NULL, CHANGE idextension idextension INT DEFAULT NULL, CHANGE idrama idrama INT DEFAULT NULL, CHANGE tipomoneda tipomoneda INT DEFAULT NULL, CHANGE FechaSolicitud FechaSolicitud DATETIME DEFAULT \'NULL\', CHANGE Presentada Presentada TINYINT(1) DEFAULT \'NULL\', CHANGE Aprobada Aprobada TINYINT(1) DEFAULT \'NULL\', CHANGE FechaAprobacion FechaAprobacion DATETIME DEFAULT \'NULL\', CHANGE FechaEmision FechaEmision DATETIME DEFAULT \'NULL\', CHANGE FechaEntrega FechaEntrega DATETIME DEFAULT \'NULL\', CHANGE limitacion limitacion INT DEFAULT NULL, CHANGE TpoMedioAmparado TpoMedioAmparado INT DEFAULT NULL, CHANGE Duracion Duracion INT DEFAULT NULL, CHANGE FechaDeCancelacion FechaDeCancelacion DATETIME DEFAULT \'NULL\', CHANGE FechaRenov FechaRenov DATETIME DEFAULT \'NULL\', CHANGE Posteada Posteada TINYINT(1) DEFAULT \'NULL\', CHANGE MediaTarifa MediaTarifa TINYINT(1) DEFAULT \'NULL\', CHANGE MedidaDelTiempo MedidaDelTiempo VARCHAR(4) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE NumFolio NumFolio VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE FechaAprobInicial FechaAprobInicial DATETIME DEFAULT \'NULL\', CHANGE TipoSolicitud TipoSolicitud INT DEFAULT NULL, CHANGE CausaDeCancelacion CausaDeCancelacion INT DEFAULT NULL, CHANGE ProrrogadoEnDias ProrrogadoEnDias SMALLINT DEFAULT NULL, CHANGE FechaDeDestruccion FechaDeDestruccion DATETIME DEFAULT \'NULL\', CHANGE Duplicado Duplicado TINYINT(1) DEFAULT \'NULL\', CHANGE IdEntidad IdEntidad VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE IDTipo IDTipo INT DEFAULT NULL, CHANGE IDServicio IDServicio INT DEFAULT NULL, CHANGE ServicioAmparado ServicioAmparado INT DEFAULT NULL, CHANGE IDEstado IDEstado INT DEFAULT NULL');
        $this->addSql('ALTER TABLE municipios CHANGE provinciaid provinciaid INT DEFAULT NULL, CHANGE s_GUID s_GUID VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Codigo Codigo INT DEFAULT NULL, CHANGE Municipio Municipio VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE organismos CHANGE Descripcion Descripcion VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE `Desc` `Desc` VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE personasjuridicas CHANGE idorga idorga INT DEFAULT NULL, CHANGE idmunicipio idmunicipio INT DEFAULT NULL, CHANGE CodReeup CodReeup VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE NomEntidad NomEntidad VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Telefono Telefono VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Email Email VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Direccion Direccion VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Actividad Actividad VARCHAR(2) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Rama Rama VARCHAR(2) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE SubRama SubRama VARCHAR(2) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE NoContribuyente NoContribuyente VARCHAR(15) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Representante Representante VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE provincias CHANGE s_GUID s_GUID VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Provincias Provincias VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE usuario CHANGE rol_id rol_id INT DEFAULT NULL, CHANGE idmunicipio idmunicipio INT DEFAULT NULL');
    }
}
