<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210115182453 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE basificacion CHANGE idlicencia idlicencia VARCHAR(9) DEFAULT NULL, CHANGE idmun idmun INT DEFAULT NULL');
        $this->addSql('ALTER TABLE causa_cancelacion_lot CHANGE clegal clegal VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE compestab CHANGE estado_comp_id estado_comp_id INT DEFAULT NULL, CHANGE c_cancel_id c_cancel_id INT DEFAULT NULL, CHANGE extension_id_id extension_id_id INT DEFAULT NULL, CHANGE folio folio VARCHAR(255) DEFAULT NULL, CHANGE fimpreso fimpreso DATE DEFAULT NULL, CHANGE fentrega fentrega DATE DEFAULT NULL, CHANGE fcancel fcancel DATE DEFAULT NULL, CHANGE c_suspencion c_suspencion VARCHAR(255) DEFAULT NULL, CHANGE finicio_susp finicio_susp DATE DEFAULT NULL, CHANGE ffin_susp ffin_susp DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE comprobante CHANGE lot lot VARCHAR(9) DEFAULT NULL, CHANGE extension_id extension_id INT DEFAULT NULL, CHANGE estado_comp_id estado_comp_id INT DEFAULT NULL, CHANGE c_cancel_id c_cancel_id INT DEFAULT NULL, CHANGE c_suspencion_id c_suspencion_id INT DEFAULT NULL, CHANGE folio folio VARCHAR(255) DEFAULT NULL, CHANGE fimpreso fimpreso DATE DEFAULT NULL, CHANGE fentrega fentrega DATE DEFAULT NULL, CHANGE fcancel fcancel DATE DEFAULT NULL, CHANGE finicio_susp finicio_susp DATE DEFAULT NULL, CHANGE ffin_susp ffin_susp DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE direccion_nacional CHANGE telefonos telefonos VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE direccion_provincial CHANGE subdir_gral_id subdir_gral_id INT DEFAULT NULL, CHANGE firmalot_id firmalot_id INT DEFAULT NULL, CHANGE firmacomp_id firmacomp_id INT DEFAULT NULL, CHANGE telefonos telefonos VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE establecimientos CHANGE licencia licencia VARCHAR(9) DEFAULT NULL, CHANGE tpoauxcon tpoauxcon INT DEFAULT NULL, CHANGE tposerv tposerv INT DEFAULT NULL, CHANGE NombreEstab NombreEstab VARCHAR(70) DEFAULT NULL, CHANGE LugarDeUbicacion LugarDeUbicacion VARCHAR(90) DEFAULT NULL, CHANGE Aseguramiento Aseguramiento TINYINT(1) DEFAULT NULL, CHANGE NumComp NumComp VARCHAR(10) DEFAULT NULL, CHANGE FechaDeEmision FechaDeEmision DATE DEFAULT NULL, CHANGE FechaEntrega FechaEntrega DATE DEFAULT NULL, CHANGE EstadoEstab EstadoEstab INT DEFAULT NULL, CHANGE Posteado Posteado TINYINT(1) DEFAULT NULL, CHANGE MediaTarifa MediaTarifa TINYINT(1) DEFAULT NULL, CHANGE AnosVigencia AnosVigencia INT DEFAULT NULL, CHANGE MedidaDelTiempo MedidaDelTiempo VARCHAR(4) DEFAULT NULL, CHANGE Duplicado Duplicado TINYINT(1) DEFAULT NULL, CHANGE Municipio Municipio INT DEFAULT NULL, CHANGE importe importe DOUBLE PRECISION DEFAULT NULL, CHANGE FechaDeCancelacion FechaDeCancelacion DATE DEFAULT NULL, CHANGE CausadeCancelacion CausadeCancelacion VARCHAR(255) DEFAULT NULL, CHANGE FechaImpresion FechaImpresion DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE foliocomprobantes CHANGE Folio Folio VARCHAR(10) NOT NULL, CHANGE Licencia Licencia VARCHAR(9) DEFAULT NULL, CHANGE Chapa Chapa VARCHAR(9) DEFAULT NULL, CHANGE ColorTipo ColorTipo VARCHAR(2) DEFAULT NULL, CHANGE FechaEmitido FechaEmitido DATETIME DEFAULT NULL, CHANGE FechaEntrega FechaEntrega DATETIME DEFAULT NULL, CHANGE EstadoModeloLot EstadoModeloLot SMALLINT DEFAULT NULL, CHANGE FechaDeCancelacion FechaDeCancelacion DATETIME DEFAULT NULL, CHANGE CausadeCancelacion CausadeCancelacion SMALLINT DEFAULT NULL, CHANGE FechaImpresion FechaImpresion DATETIME DEFAULT NULL, CHANGE SinCosto SinCosto TINYINT(1) DEFAULT NULL, CHANGE Duplicado Duplicado TINYINT(1) DEFAULT NULL, CHANGE Moneda Moneda INT DEFAULT NULL, CHANGE Extension Extension SMALLINT DEFAULT NULL, CHANGE Importe Importe DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE lotjuridicas CHANGE idtramitador idtramitador INT DEFAULT NULL, CHANGE idaprueba idaprueba INT DEFAULT NULL, CHANGE idextension idextension INT DEFAULT NULL, CHANGE idrama idrama INT DEFAULT NULL, CHANGE causadecancelacion_id causadecancelacion_id INT DEFAULT NULL, CHANGE causa_suspension_id causa_suspension_id INT DEFAULT NULL, CHANGE FechaSolicitud FechaSolicitud DATETIME DEFAULT NULL, CHANGE Presentada Presentada TINYINT(1) DEFAULT NULL, CHANGE Aprobada Aprobada TINYINT(1) DEFAULT NULL, CHANGE FechaAprobacion FechaAprobacion DATETIME DEFAULT NULL, CHANGE FechaEmision FechaEmision DATETIME DEFAULT NULL, CHANGE FechaEntrega FechaEntrega DATETIME DEFAULT NULL, CHANGE limitacion limitacion INT DEFAULT NULL, CHANGE TpoMedioAmparado TpoMedioAmparado INT DEFAULT NULL, CHANGE Duracion Duracion INT DEFAULT NULL, CHANGE FechaDeCancelacion FechaDeCancelacion DATETIME DEFAULT NULL, CHANGE FechaRenov FechaRenov DATETIME DEFAULT NULL, CHANGE Posteada Posteada TINYINT(1) DEFAULT NULL, CHANGE MediaTarifa MediaTarifa TINYINT(1) DEFAULT NULL, CHANGE NumFolio NumFolio VARCHAR(10) DEFAULT NULL, CHANGE FechaAprobInicial FechaAprobInicial DATETIME DEFAULT NULL, CHANGE TipoSolicitud TipoSolicitud INT DEFAULT NULL, CHANGE ProrrogadoEnDias ProrrogadoEnDias SMALLINT DEFAULT NULL, CHANGE FechaDeDestruccion FechaDeDestruccion DATETIME DEFAULT NULL, CHANGE Duplicado Duplicado TINYINT(1) DEFAULT NULL, CHANGE IdEntidad IdEntidad VARCHAR(50) DEFAULT NULL, CHANGE IDTipo IDTipo INT DEFAULT NULL, CHANGE IDServicio IDServicio INT DEFAULT NULL, CHANGE ServicioAmparado ServicioAmparado INT DEFAULT NULL, CHANGE IDEstado IDEstado INT DEFAULT NULL, CHANGE fimpresion fimpresion DATE DEFAULT NULL, CHANGE fecha_suspension fecha_suspension DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE medios_trans CHANGE rama rama INT DEFAULT NULL, CHANGE tipomedio tipomedio INT DEFAULT NULL, CHANGE estado_medio_id estado_medio_id INT DEFAULT NULL, CHANGE basificacion basificacion VARCHAR(255) DEFAULT NULL, CHANGE cap cap DOUBLE PRECISION DEFAULT NULL, CHANGE umcap umcap INT DEFAULT NULL, CHANGE marca marca VARCHAR(255) DEFAULT NULL, CHANGE modelo modelo VARCHAR(255) DEFAULT NULL, CHANGE ind_consumo ind_consumo DOUBLE PRECISION DEFAULT NULL, CHANGE potencia potencia INT DEFAULT NULL, CHANGE num_rev_tecnica num_rev_tecnica VARCHAR(255) DEFAULT NULL, CHANGE venc_rev_tecnica venc_rev_tecnica DATE DEFAULT NULL, CHANGE pais_abanderamiento pais_abanderamiento VARCHAR(255) DEFAULT NULL, CHANGE id_tipo id_tipo INT DEFAULT NULL, CHANGE basificacionObj basificacionObj VARCHAR(20) DEFAULT NULL, CHANGE tipoPropiedad tipoPropiedad INT DEFAULT NULL, CHANGE tipoCombustible tipoCombustible INT DEFAULT NULL, CHANGE servicios_especiales servicios_especiales VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE municipios CHANGE provinciaid provinciaid INT DEFAULT NULL, CHANGE s_GUID s_GUID VARCHAR(50) DEFAULT NULL, CHANGE Codigo Codigo INT DEFAULT NULL, CHANGE Municipio Municipio VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE oficina_mcpal CHANGE direccion_provincial_id direccion_provincial_id INT DEFAULT NULL, CHANGE firmalot_id firmalot_id INT DEFAULT NULL, CHANGE firmacomp_id firmacomp_id INT DEFAULT NULL, CHANGE direccion direccion VARCHAR(255) DEFAULT NULL, CHANGE telefono telefono INT DEFAULT NULL, CHANGE email email VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE organismos CHANGE Descripcion Descripcion VARCHAR(200) DEFAULT NULL, CHANGE `Desc` `Desc` VARCHAR(200) DEFAULT NULL');
        $this->addSql('ALTER TABLE personasjuridicas CHANGE idorga idorga INT DEFAULT NULL, CHANGE idmunicipio idmunicipio INT DEFAULT NULL, CHANGE CodReeup CodReeup VARCHAR(50) DEFAULT NULL, CHANGE Telefono Telefono VARCHAR(20) DEFAULT NULL, CHANGE Email Email VARCHAR(50) DEFAULT NULL, CHANGE Direccion Direccion VARCHAR(200) DEFAULT NULL, CHANGE Actividad Actividad VARCHAR(2) DEFAULT NULL, CHANGE Rama Rama VARCHAR(2) DEFAULT NULL, CHANGE SubRama SubRama VARCHAR(2) DEFAULT NULL, CHANGE NoContribuyente NoContribuyente VARCHAR(15) DEFAULT NULL, CHANGE Representante Representante VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE provincias CHANGE s_GUID s_GUID VARCHAR(50) DEFAULT NULL, CHANGE Provincias Provincias VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE tipo_serv_aux_con CHANGE rama_id rama_id INT DEFAULT NULL, CHANGE id_est_new_res id_est_new_res INT DEFAULT NULL');
        $this->addSql('ALTER TABLE tipomedio CHANGE Medios Medios VARCHAR(50) DEFAULT NULL, CHANGE Rama Rama INT DEFAULT NULL, CHANGE TipoAnexo1 TipoAnexo1 INT DEFAULT NULL, CHANGE TipoParteOperativo TipoParteOperativo INT DEFAULT NULL');
        $this->addSql('ALTER TABLE tipotramite ADD remunerado TINYINT(1) NOT NULL, ADD importe DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE tramite CHANGE aprueba_id aprueba_id INT DEFAULT NULL, CHANGE iporigen iporigen VARCHAR(255) DEFAULT NULL, CHANGE observaciones observaciones VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE user CHANGE oficina_mcpal_id oficina_mcpal_id INT DEFAULT NULL, CHANGE direccion_provincial_id direccion_provincial_id INT DEFAULT NULL, CHANGE cargo_id cargo_id INT DEFAULT NULL, CHANGE roles roles JSON NOT NULL, CHANGE nombre_apellidos nombre_apellidos VARCHAR(255) DEFAULT NULL, CHANGE carnet_funcionario carnet_funcionario VARCHAR(255) DEFAULT NULL, CHANGE fecha_contratacion fecha_contratacion DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE usuario CHANGE rol_id rol_id INT DEFAULT NULL, CHANGE idmunicipio idmunicipio INT DEFAULT NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE basificacion CHANGE idlicencia idlicencia VARCHAR(9) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE idmun idmun INT DEFAULT NULL');
        $this->addSql('ALTER TABLE causa_cancelacion_lot CHANGE clegal clegal VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE compestab CHANGE estado_comp_id estado_comp_id INT DEFAULT NULL, CHANGE c_cancel_id c_cancel_id INT DEFAULT NULL, CHANGE extension_id_id extension_id_id INT DEFAULT NULL, CHANGE folio folio VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE fimpreso fimpreso DATE DEFAULT \'NULL\', CHANGE fentrega fentrega DATE DEFAULT \'NULL\', CHANGE fcancel fcancel DATE DEFAULT \'NULL\', CHANGE c_suspencion c_suspencion VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE finicio_susp finicio_susp DATE DEFAULT \'NULL\', CHANGE ffin_susp ffin_susp DATE DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE comprobante CHANGE lot lot VARCHAR(9) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE extension_id extension_id INT DEFAULT NULL, CHANGE estado_comp_id estado_comp_id INT DEFAULT NULL, CHANGE c_cancel_id c_cancel_id INT DEFAULT NULL, CHANGE c_suspencion_id c_suspencion_id INT DEFAULT NULL, CHANGE folio folio VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE fimpreso fimpreso DATE DEFAULT \'NULL\', CHANGE fentrega fentrega DATE DEFAULT \'NULL\', CHANGE fcancel fcancel DATE DEFAULT \'NULL\', CHANGE finicio_susp finicio_susp DATE DEFAULT \'NULL\', CHANGE ffin_susp ffin_susp DATE DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE direccion_nacional CHANGE telefonos telefonos VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE direccion_provincial CHANGE subdir_gral_id subdir_gral_id INT DEFAULT NULL, CHANGE firmalot_id firmalot_id INT DEFAULT NULL, CHANGE firmacomp_id firmacomp_id INT DEFAULT NULL, CHANGE telefonos telefonos VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE establecimientos CHANGE licencia licencia VARCHAR(9) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE tpoauxcon tpoauxcon INT DEFAULT NULL, CHANGE tposerv tposerv INT DEFAULT NULL, CHANGE NombreEstab NombreEstab VARCHAR(70) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE LugarDeUbicacion LugarDeUbicacion VARCHAR(90) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Aseguramiento Aseguramiento TINYINT(1) DEFAULT \'NULL\', CHANGE NumComp NumComp VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE FechaDeEmision FechaDeEmision DATE DEFAULT \'NULL\', CHANGE FechaEntrega FechaEntrega DATE DEFAULT \'NULL\', CHANGE EstadoEstab EstadoEstab INT DEFAULT NULL, CHANGE Posteado Posteado TINYINT(1) DEFAULT \'NULL\', CHANGE MediaTarifa MediaTarifa TINYINT(1) DEFAULT \'NULL\', CHANGE AnosVigencia AnosVigencia INT DEFAULT NULL, CHANGE MedidaDelTiempo MedidaDelTiempo VARCHAR(4) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Duplicado Duplicado TINYINT(1) DEFAULT \'NULL\', CHANGE FechaDeCancelacion FechaDeCancelacion DATE DEFAULT \'NULL\', CHANGE CausadeCancelacion CausadeCancelacion VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE FechaImpresion FechaImpresion DATE DEFAULT \'NULL\', CHANGE importe importe DOUBLE PRECISION DEFAULT \'NULL\', CHANGE Municipio Municipio INT DEFAULT NULL');
        $this->addSql('ALTER TABLE foliocomprobantes CHANGE Folio Folio VARCHAR(10) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE Licencia Licencia VARCHAR(9) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Chapa Chapa VARCHAR(9) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ColorTipo ColorTipo VARCHAR(2) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE FechaEmitido FechaEmitido DATETIME DEFAULT \'NULL\', CHANGE FechaEntrega FechaEntrega DATETIME DEFAULT \'NULL\', CHANGE EstadoModeloLot EstadoModeloLot SMALLINT DEFAULT NULL, CHANGE FechaDeCancelacion FechaDeCancelacion DATETIME DEFAULT \'NULL\', CHANGE CausadeCancelacion CausadeCancelacion SMALLINT DEFAULT NULL, CHANGE FechaImpresion FechaImpresion DATETIME DEFAULT \'NULL\', CHANGE SinCosto SinCosto TINYINT(1) DEFAULT \'NULL\', CHANGE Duplicado Duplicado TINYINT(1) DEFAULT \'NULL\', CHANGE Moneda Moneda INT DEFAULT NULL, CHANGE Extension Extension SMALLINT DEFAULT NULL, CHANGE Importe Importe DOUBLE PRECISION DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE lotjuridicas CHANGE idtramitador idtramitador INT DEFAULT NULL, CHANGE idaprueba idaprueba INT DEFAULT NULL, CHANGE idextension idextension INT DEFAULT NULL, CHANGE idrama idrama INT DEFAULT NULL, CHANGE causadecancelacion_id causadecancelacion_id INT DEFAULT NULL, CHANGE causa_suspension_id causa_suspension_id INT DEFAULT NULL, CHANGE FechaSolicitud FechaSolicitud DATETIME DEFAULT \'NULL\', CHANGE Presentada Presentada TINYINT(1) DEFAULT \'NULL\', CHANGE Aprobada Aprobada TINYINT(1) DEFAULT \'NULL\', CHANGE FechaAprobacion FechaAprobacion DATETIME DEFAULT \'NULL\', CHANGE FechaEmision FechaEmision DATETIME DEFAULT \'NULL\', CHANGE FechaEntrega FechaEntrega DATETIME DEFAULT \'NULL\', CHANGE limitacion limitacion INT DEFAULT NULL, CHANGE TpoMedioAmparado TpoMedioAmparado INT DEFAULT NULL, CHANGE Duracion Duracion INT DEFAULT NULL, CHANGE FechaDeCancelacion FechaDeCancelacion DATETIME DEFAULT \'NULL\', CHANGE FechaRenov FechaRenov DATETIME DEFAULT \'NULL\', CHANGE Posteada Posteada TINYINT(1) DEFAULT \'NULL\', CHANGE MediaTarifa MediaTarifa TINYINT(1) DEFAULT \'NULL\', CHANGE NumFolio NumFolio VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE FechaAprobInicial FechaAprobInicial DATETIME DEFAULT \'NULL\', CHANGE TipoSolicitud TipoSolicitud INT DEFAULT NULL, CHANGE ProrrogadoEnDias ProrrogadoEnDias SMALLINT DEFAULT NULL, CHANGE FechaDeDestruccion FechaDeDestruccion DATETIME DEFAULT \'NULL\', CHANGE Duplicado Duplicado TINYINT(1) DEFAULT \'NULL\', CHANGE fimpresion fimpresion DATE DEFAULT \'NULL\', CHANGE fecha_suspension fecha_suspension DATE DEFAULT \'NULL\', CHANGE IdEntidad IdEntidad VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE IDTipo IDTipo INT DEFAULT NULL, CHANGE IDServicio IDServicio INT DEFAULT NULL, CHANGE ServicioAmparado ServicioAmparado INT DEFAULT NULL, CHANGE IDEstado IDEstado INT DEFAULT NULL');
        $this->addSql('ALTER TABLE medios_trans CHANGE tipomedio tipomedio INT DEFAULT NULL, CHANGE estado_medio_id estado_medio_id INT DEFAULT NULL, CHANGE rama rama INT DEFAULT NULL, CHANGE basificacion basificacion VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE cap cap DOUBLE PRECISION DEFAULT \'NULL\', CHANGE umcap umcap INT DEFAULT NULL, CHANGE marca marca VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE modelo modelo VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ind_consumo ind_consumo DOUBLE PRECISION DEFAULT \'NULL\', CHANGE potencia potencia INT DEFAULT NULL, CHANGE num_rev_tecnica num_rev_tecnica VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE venc_rev_tecnica venc_rev_tecnica DATE DEFAULT \'NULL\', CHANGE pais_abanderamiento pais_abanderamiento VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE id_tipo id_tipo INT DEFAULT NULL, CHANGE servicios_especiales servicios_especiales VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE tipoCombustible tipoCombustible INT DEFAULT NULL, CHANGE tipoPropiedad tipoPropiedad INT DEFAULT NULL, CHANGE basificacionObj basificacionObj VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE municipios CHANGE provinciaid provinciaid INT DEFAULT NULL, CHANGE s_GUID s_GUID VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Codigo Codigo INT DEFAULT NULL, CHANGE Municipio Municipio VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE oficina_mcpal CHANGE direccion_provincial_id direccion_provincial_id INT DEFAULT NULL, CHANGE firmalot_id firmalot_id INT DEFAULT NULL, CHANGE firmacomp_id firmacomp_id INT DEFAULT NULL, CHANGE direccion direccion VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE telefono telefono INT DEFAULT NULL, CHANGE email email VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE organismos CHANGE Descripcion Descripcion VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE `Desc` `Desc` VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE personasjuridicas CHANGE idorga idorga INT DEFAULT NULL, CHANGE idmunicipio idmunicipio INT DEFAULT NULL, CHANGE CodReeup CodReeup VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Telefono Telefono VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Email Email VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Direccion Direccion VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Actividad Actividad VARCHAR(2) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Rama Rama VARCHAR(2) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE SubRama SubRama VARCHAR(2) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE NoContribuyente NoContribuyente VARCHAR(15) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Representante Representante VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE provincias CHANGE s_GUID s_GUID VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Provincias Provincias VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE tipo_serv_aux_con CHANGE rama_id rama_id INT DEFAULT NULL, CHANGE id_est_new_res id_est_new_res INT DEFAULT NULL');
        $this->addSql('ALTER TABLE tipomedio CHANGE Medios Medios VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Rama Rama INT DEFAULT NULL, CHANGE TipoAnexo1 TipoAnexo1 INT DEFAULT NULL, CHANGE TipoParteOperativo TipoParteOperativo INT DEFAULT NULL');
        $this->addSql('ALTER TABLE tipotramite DROP remunerado, DROP importe');
        $this->addSql('ALTER TABLE tramite CHANGE aprueba_id aprueba_id INT DEFAULT NULL, CHANGE iporigen iporigen VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE observaciones observaciones VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE user CHANGE oficina_mcpal_id oficina_mcpal_id INT DEFAULT NULL, CHANGE direccion_provincial_id direccion_provincial_id INT DEFAULT NULL, CHANGE cargo_id cargo_id INT DEFAULT NULL, CHANGE roles roles LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_bin`, CHANGE nombre_apellidos nombre_apellidos VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE carnet_funcionario carnet_funcionario VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE fecha_contratacion fecha_contratacion DATE DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE usuario CHANGE rol_id rol_id INT DEFAULT NULL, CHANGE idmunicipio idmunicipio INT DEFAULT NULL');
    }
}
