<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200708193927 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE basificacion CHANGE idmun idmun INT DEFAULT NULL, CHANGE idlicencia idlicencia VARCHAR(9) DEFAULT NULL, CHANGE NombreLB NombreLB VARCHAR(200) DEFAULT NULL, CHANGE Direccion Direccion VARCHAR(200) DEFAULT NULL');
        $this->addSql('ALTER TABLE comp_mt ADD medio_trans_id VARCHAR(20) DEFAULT NULL, DROP medio_trans, DROP est_comp, CHANGE folio_id folio_id VARCHAR(255) DEFAULT NULL, CHANGE ccancelacion ccancelacion INT DEFAULT NULL, CHANGE sin_costo sin_costo TINYINT(1) DEFAULT NULL, CHANGE duplicado duplicado TINYINT(1) DEFAULT NULL, CHANGE servpers servpers VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE comp_mt ADD CONSTRAINT FK_34D6EEAB22479983 FOREIGN KEY (medio_trans_id) REFERENCES medios_trans (id)');
        $this->addSql('CREATE INDEX IDX_34D6EEAB22479983 ON comp_mt (medio_trans_id)');
        $this->addSql('ALTER TABLE est_comp ADD comp_mt_id INT DEFAULT NULL, DROP comp_mt, CHANGE ffin ffin DATE DEFAULT NULL, CHANGE observacion observacion VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE est_comp ADD CONSTRAINT FK_E0171CEB1C21DE06 FOREIGN KEY (comp_mt_id) REFERENCES comp_mt (id)');
        $this->addSql('CREATE INDEX IDX_E0171CEB1C21DE06 ON est_comp (comp_mt_id)');
        $this->addSql('ALTER TABLE foliocomprobantes CHANGE Folio Folio VARCHAR(10) NOT NULL, CHANGE Licencia Licencia VARCHAR(9) DEFAULT NULL, CHANGE Chapa Chapa VARCHAR(9) DEFAULT NULL, CHANGE ColorTipo ColorTipo VARCHAR(2) DEFAULT NULL, CHANGE FechaEmitido FechaEmitido DATETIME DEFAULT NULL, CHANGE FechaEntrega FechaEntrega DATETIME DEFAULT NULL, CHANGE EstadoModeloLot EstadoModeloLot SMALLINT DEFAULT NULL, CHANGE FechaDeCancelacion FechaDeCancelacion DATETIME DEFAULT NULL, CHANGE CausadeCancelacion CausadeCancelacion SMALLINT DEFAULT NULL, CHANGE FechaImpresion FechaImpresion DATETIME DEFAULT NULL, CHANGE SinCosto SinCosto TINYINT(1) DEFAULT NULL, CHANGE Duplicado Duplicado TINYINT(1) DEFAULT NULL, CHANGE Moneda Moneda INT DEFAULT NULL, CHANGE Extension Extension SMALLINT DEFAULT NULL, CHANGE Importe Importe DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE lotjuridicas CHANGE idtramitador idtramitador INT DEFAULT NULL, CHANGE idaprueba idaprueba INT DEFAULT NULL, CHANGE idextension idextension INT DEFAULT NULL, CHANGE idrama idrama INT DEFAULT NULL, CHANGE tipomoneda tipomoneda INT DEFAULT NULL, CHANGE FechaSolicitud FechaSolicitud DATETIME DEFAULT NULL, CHANGE Presentada Presentada TINYINT(1) DEFAULT NULL, CHANGE Aprobada Aprobada TINYINT(1) DEFAULT NULL, CHANGE FechaAprobacion FechaAprobacion DATETIME DEFAULT NULL, CHANGE FechaEmision FechaEmision DATETIME DEFAULT NULL, CHANGE FechaEntrega FechaEntrega DATETIME DEFAULT NULL, CHANGE limitacion limitacion INT DEFAULT NULL, CHANGE TpoMedioAmparado TpoMedioAmparado INT DEFAULT NULL, CHANGE Duracion Duracion INT DEFAULT NULL, CHANGE FechaDeCancelacion FechaDeCancelacion DATETIME DEFAULT NULL, CHANGE FechaRenov FechaRenov DATETIME DEFAULT NULL, CHANGE Posteada Posteada TINYINT(1) DEFAULT NULL, CHANGE MediaTarifa MediaTarifa TINYINT(1) DEFAULT NULL, CHANGE MedidaDelTiempo MedidaDelTiempo VARCHAR(4) DEFAULT NULL, CHANGE NumFolio NumFolio VARCHAR(10) DEFAULT NULL, CHANGE FechaAprobInicial FechaAprobInicial DATETIME DEFAULT NULL, CHANGE TipoSolicitud TipoSolicitud INT DEFAULT NULL, CHANGE CausaDeCancelacion CausaDeCancelacion INT DEFAULT NULL, CHANGE ProrrogadoEnDias ProrrogadoEnDias SMALLINT DEFAULT NULL, CHANGE FechaDeDestruccion FechaDeDestruccion DATETIME DEFAULT NULL, CHANGE Duplicado Duplicado TINYINT(1) DEFAULT NULL, CHANGE IdEntidad IdEntidad VARCHAR(255) DEFAULT NULL, CHANGE IDTipo IDTipo INT DEFAULT NULL, CHANGE IDServicio IDServicio INT DEFAULT NULL, CHANGE ServicioAmparado ServicioAmparado INT DEFAULT NULL, CHANGE IDEstado IDEstado INT DEFAULT NULL');
        $this->addSql('ALTER TABLE medios_trans CHANGE basificacion basificacion VARCHAR(255) DEFAULT NULL, CHANGE cap cap DOUBLE PRECISION DEFAULT NULL, CHANGE umcap umcap INT DEFAULT NULL, CHANGE marca marca VARCHAR(255) DEFAULT NULL, CHANGE modelo modelo VARCHAR(255) DEFAULT NULL, CHANGE servicios_especiales servicios_especiales INT DEFAULT NULL, CHANGE ind_consumo ind_consumo DOUBLE PRECISION DEFAULT NULL, CHANGE potencia potencia INT DEFAULT NULL, CHANGE tipo_propiedad tipo_propiedad INT DEFAULT NULL, CHANGE num_rev_tecnica num_rev_tecnica VARCHAR(255) DEFAULT NULL, CHANGE venc_rev_tecnica venc_rev_tecnica DATE DEFAULT NULL, CHANGE pais_abanderamiento pais_abanderamiento VARCHAR(255) DEFAULT NULL, CHANGE id_tipo id_tipo INT DEFAULT NULL');
        $this->addSql('ALTER TABLE municipios CHANGE provinciaid provinciaid INT DEFAULT NULL, CHANGE s_GUID s_GUID VARCHAR(50) DEFAULT NULL, CHANGE Codigo Codigo INT DEFAULT NULL, CHANGE Municipio Municipio VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE organismos CHANGE Descripcion Descripcion VARCHAR(200) DEFAULT NULL, CHANGE `Desc` `Desc` VARCHAR(200) DEFAULT NULL');
        $this->addSql('ALTER TABLE personasjuridicas CHANGE idorga idorga INT DEFAULT NULL, CHANGE idmunicipio idmunicipio INT DEFAULT NULL, CHANGE CodReeup CodReeup VARCHAR(50) DEFAULT NULL, CHANGE NomEntidad NomEntidad VARCHAR(100) DEFAULT NULL, CHANGE Telefono Telefono VARCHAR(20) DEFAULT NULL, CHANGE Email Email VARCHAR(50) DEFAULT NULL, CHANGE Direccion Direccion VARCHAR(200) DEFAULT NULL, CHANGE Actividad Actividad VARCHAR(2) DEFAULT NULL, CHANGE Rama Rama VARCHAR(2) DEFAULT NULL, CHANGE SubRama SubRama VARCHAR(2) DEFAULT NULL, CHANGE NoContribuyente NoContribuyente VARCHAR(15) DEFAULT NULL, CHANGE Representante Representante VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE provincias CHANGE s_GUID s_GUID VARCHAR(50) DEFAULT NULL, CHANGE Provincias Provincias VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE usuario CHANGE rol_id rol_id INT DEFAULT NULL, CHANGE idmunicipio idmunicipio INT DEFAULT NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE basificacion CHANGE idlicencia idlicencia VARCHAR(9) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE idmun idmun INT DEFAULT NULL, CHANGE NombreLB NombreLB VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Direccion Direccion VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE comp_mt DROP FOREIGN KEY FK_34D6EEAB22479983');
        $this->addSql('DROP INDEX IDX_34D6EEAB22479983 ON comp_mt');
        $this->addSql('ALTER TABLE comp_mt ADD medio_trans VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, ADD est_comp VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, DROP medio_trans_id, CHANGE folio_id folio_id VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ccancelacion ccancelacion INT DEFAULT NULL, CHANGE sin_costo sin_costo TINYINT(1) DEFAULT \'NULL\', CHANGE duplicado duplicado TINYINT(1) DEFAULT \'NULL\', CHANGE servpers servpers VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE est_comp DROP FOREIGN KEY FK_E0171CEB1C21DE06');
        $this->addSql('DROP INDEX IDX_E0171CEB1C21DE06 ON est_comp');
        $this->addSql('ALTER TABLE est_comp ADD comp_mt VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, DROP comp_mt_id, CHANGE ffin ffin DATE DEFAULT \'NULL\', CHANGE observacion observacion VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE foliocomprobantes CHANGE Folio Folio VARCHAR(10) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE Licencia Licencia VARCHAR(9) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Chapa Chapa VARCHAR(9) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ColorTipo ColorTipo VARCHAR(2) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE FechaEmitido FechaEmitido DATETIME DEFAULT \'NULL\', CHANGE FechaEntrega FechaEntrega DATETIME DEFAULT \'NULL\', CHANGE EstadoModeloLot EstadoModeloLot SMALLINT DEFAULT NULL, CHANGE FechaDeCancelacion FechaDeCancelacion DATETIME DEFAULT \'NULL\', CHANGE CausadeCancelacion CausadeCancelacion SMALLINT DEFAULT NULL, CHANGE FechaImpresion FechaImpresion DATETIME DEFAULT \'NULL\', CHANGE SinCosto SinCosto TINYINT(1) DEFAULT \'NULL\', CHANGE Duplicado Duplicado TINYINT(1) DEFAULT \'NULL\', CHANGE Moneda Moneda INT DEFAULT NULL, CHANGE Extension Extension SMALLINT DEFAULT NULL, CHANGE Importe Importe DOUBLE PRECISION DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE lotjuridicas CHANGE idtramitador idtramitador INT DEFAULT NULL, CHANGE idaprueba idaprueba INT DEFAULT NULL, CHANGE idextension idextension INT DEFAULT NULL, CHANGE idrama idrama INT DEFAULT NULL, CHANGE tipomoneda tipomoneda INT DEFAULT NULL, CHANGE FechaSolicitud FechaSolicitud DATETIME DEFAULT \'NULL\', CHANGE Presentada Presentada TINYINT(1) DEFAULT \'NULL\', CHANGE Aprobada Aprobada TINYINT(1) DEFAULT \'NULL\', CHANGE FechaAprobacion FechaAprobacion DATETIME DEFAULT \'NULL\', CHANGE FechaEmision FechaEmision DATETIME DEFAULT \'NULL\', CHANGE FechaEntrega FechaEntrega DATETIME DEFAULT \'NULL\', CHANGE limitacion limitacion INT DEFAULT NULL, CHANGE TpoMedioAmparado TpoMedioAmparado INT DEFAULT NULL, CHANGE Duracion Duracion INT DEFAULT NULL, CHANGE FechaDeCancelacion FechaDeCancelacion DATETIME DEFAULT \'NULL\', CHANGE FechaRenov FechaRenov DATETIME DEFAULT \'NULL\', CHANGE Posteada Posteada TINYINT(1) DEFAULT \'NULL\', CHANGE MediaTarifa MediaTarifa TINYINT(1) DEFAULT \'NULL\', CHANGE MedidaDelTiempo MedidaDelTiempo VARCHAR(4) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE NumFolio NumFolio VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE FechaAprobInicial FechaAprobInicial DATETIME DEFAULT \'NULL\', CHANGE TipoSolicitud TipoSolicitud INT DEFAULT NULL, CHANGE CausaDeCancelacion CausaDeCancelacion INT DEFAULT NULL, CHANGE ProrrogadoEnDias ProrrogadoEnDias SMALLINT DEFAULT NULL, CHANGE FechaDeDestruccion FechaDeDestruccion DATETIME DEFAULT \'NULL\', CHANGE Duplicado Duplicado TINYINT(1) DEFAULT \'NULL\', CHANGE IdEntidad IdEntidad VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE IDTipo IDTipo INT DEFAULT NULL, CHANGE IDServicio IDServicio INT DEFAULT NULL, CHANGE ServicioAmparado ServicioAmparado INT DEFAULT NULL, CHANGE IDEstado IDEstado INT DEFAULT NULL');
        $this->addSql('ALTER TABLE medios_trans CHANGE basificacion basificacion VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE cap cap DOUBLE PRECISION DEFAULT \'NULL\', CHANGE umcap umcap INT DEFAULT NULL, CHANGE marca marca VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE modelo modelo VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE servicios_especiales servicios_especiales INT DEFAULT NULL, CHANGE ind_consumo ind_consumo DOUBLE PRECISION DEFAULT \'NULL\', CHANGE potencia potencia INT DEFAULT NULL, CHANGE tipo_propiedad tipo_propiedad INT DEFAULT NULL, CHANGE num_rev_tecnica num_rev_tecnica VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE venc_rev_tecnica venc_rev_tecnica DATE DEFAULT \'NULL\', CHANGE pais_abanderamiento pais_abanderamiento VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE id_tipo id_tipo INT DEFAULT NULL');
        $this->addSql('ALTER TABLE municipios CHANGE provinciaid provinciaid INT DEFAULT NULL, CHANGE s_GUID s_GUID VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Codigo Codigo INT DEFAULT NULL, CHANGE Municipio Municipio VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE organismos CHANGE Descripcion Descripcion VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE `Desc` `Desc` VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE personasjuridicas CHANGE idorga idorga INT DEFAULT NULL, CHANGE idmunicipio idmunicipio INT DEFAULT NULL, CHANGE CodReeup CodReeup VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE NomEntidad NomEntidad VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Telefono Telefono VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Email Email VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Direccion Direccion VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Actividad Actividad VARCHAR(2) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Rama Rama VARCHAR(2) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE SubRama SubRama VARCHAR(2) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE NoContribuyente NoContribuyente VARCHAR(15) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Representante Representante VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE provincias CHANGE s_GUID s_GUID VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE Provincias Provincias VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE usuario CHANGE rol_id rol_id INT DEFAULT NULL, CHANGE idmunicipio idmunicipio INT DEFAULT NULL');
    }
}
